
require 'key-menu'.set('n', '<localleader>i', {desc='Insert...'})
vim.keymap.set('n', '<localleader>iv', ":lua elixir_insert_inspect_value()<cr>", {desc="elixir add inspect value"})
vim.keymap.set('n', '<localleader>ip', ":lua elixir_insert_inspect_param()<cr>", {desc="elixir add inspect parameter"})
vim.keymap.set('n', '<localleader>il', ":lua elixir_insert_inspect_label()<cr>", {desc="elixir add inspect label"})
vim.keymap.set('n', '<localleader>if', ":lua elixir_insert_inspect_field()<cr>", {desc="elixir add inspect field"})
require 'key-menu'.set('n', '<localleader>a', {desc='API'})
vim.keymap.set('n', '<localleader>ac', ":lua require'elixir-extras'.elixir_view_docs({})<cr>", {desc="elixir apidocs (core only)"})
vim.keymap.set('n', '<localleader>aa', ":lua require'elixir-extras'.elixir_view_docs({include_mix_libs=true})<cr>", {desc="elixir apidocs (all)"})
require 'key-menu'.set('n', '<localleader>o', {desc='Open...'})
vim.keymap.set('n', '<localleader>os', ":lua telescope_elixir_stacktrace({})<cr>", {desc="elixir open stacktrace"})
require 'key-menu'.set('n', '<localleader>m', {desc='match/module...'})
vim.keymap.set('n', '<localleader>mi', ":lua elixir_match_error_details_indent({})<cr>", {desc="elixir indent match error details"})
vim.keymap.set('n', '<localleader>mc', ":lua require'elixir-extras'.module_complete()<cr>", {desc="elixir module complete"})
