
require 'key-menu'.set('n', '<localleader>i', {desc='Inspect...', buffer = true})
vim.keymap.set('n', '<localleader>iv', ":lua elixir_insert_inspect_value()<cr>", {desc="elixir add inspect value", buffer = true})
vim.keymap.set('n', '<localleader>ip', ":lua elixir_insert_inspect_param()<cr>", {desc="elixir add inspect parameter", buffer = true})
vim.keymap.set('n', '<localleader>il', ":lua elixir_insert_inspect_label()<cr>", {desc="elixir add inspect label", buffer = true})
vim.keymap.set('n', '<localleader>if', ":lua elixir_insert_inspect_field()<cr>", {desc="elixir add inspect field", buffer = true})
require 'key-menu'.set('n', '<localleader>a', {desc='API', buffer = true})
vim.keymap.set('n', '<localleader>ac', ":lua require'elixir-extras'.elixir_view_docs({})<cr>", {desc="elixir apidocs (core only)", buffer = true})
vim.keymap.set('n', '<localleader>aa', ":lua require'elixir-extras'.elixir_view_docs({include_mix_libs=true})<cr>", {desc="elixir apidocs (all)", buffer = true})
require 'key-menu'.set('n', '<localleader>o', {desc='Open...', buffer = true})
vim.keymap.set('n', '<localleader>os', ":lua telescope_elixir_stacktrace({})<cr>", {desc="elixir open stacktrace", buffer = true})
require 'key-menu'.set('n', '<localleader>m', {desc='match/module...', buffer = true})
vim.keymap.set('n', '<localleader>mi', ":lua elixir_match_error_details_indent({})<cr>", {desc="elixir indent match error details", buffer = true})
vim.keymap.set('n', '<localleader>mc', ":lua require'elixir-extras'.module_complete()<cr>", {desc="elixir module complete", buffer = true})
